language: python
python:
  - "2.7"
env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib
before_install:
  - "./.travis.sh"
  - pip install coverage
  - pip install git+git://git.liw.fi/coverage-test-runner
  - pip install pylibmc
  - pip install PyYAML
script:
  - python setup.py check
