language: python
python:
  - "2.7"
install:
  - pip install coverage
  - pip install git+git://git.liw.fi/coverage-test-runner
  - pip install pylibmc
  - pip install PyYAML
  - pip install pygit2
script:
  - python setup.py check
